/**
 * App Root Layout public module surface.
 */
import type { Metadata } from "next";
import { Source_Code_Pro, Source_Sans_3, Source_Serif_4 } from "next/font/google";
import Accessibility from "@/components/accessibility";
import ColorScheme from "@/components/color-scheme";
import LiveChat from "@/components/marketing/live-chat";
import { Toaster } from "@/components/ui/sonner";
import { TooltipProvider } from "@/components/ui/tooltip";

const sourceSans = Source_Sans_3({
  variable: "--font-sans",
  subsets: ["latin"],
});

const sourceSerif = Source_Serif_4({
  variable: "--font-serif",
  subsets: ["latin"],
});

const sourceMono = Source_Code_Pro({
  variable: "--font-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const accessibilityChatConfigured = Boolean(process.env.OPENROUTER_API_KEY);

  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${sourceSans.variable} ${sourceSerif.variable} ${sourceMono.variable}`}
    >
      <body className="min-h-dvh flex flex-col">
        <ColorScheme>
          <TooltipProvider>
            <Accessibility>{children}</Accessibility>
            <LiveChat apiConfigured={accessibilityChatConfigured} />
            <Toaster richColors />
          </TooltipProvider>
        </ColorScheme>
      </body>
    </html>
  );
}
