/**
 * Lib Tailwind Token Matrix public module surface.
 */
// Hand-maintained coverage manifest for variable-backed Tailwind utilities in app/globals.css.
// Keep these as literal strings so Tailwind compiles every token exercised by the pages.

/** Color utility class groups rendered by the Tailwind token matrix page. */
export const colorClasses = [
  {
    name: "accent",
    bg: "bg-accent",
    text: "text-accent",
    border: "border-accent",
    ring: "ring-accent",
    shadow: "shadow-accent",
  },
  {
    name: "accent-foreground",
    bg: "bg-accent-foreground",
    text: "text-accent-foreground",
    border: "border-accent-foreground",
    ring: "ring-accent-foreground",
    shadow: "shadow-accent-foreground",
  },
  {
    name: "accent-hover",
    bg: "bg-accent-hover",
    text: "text-accent-hover",
    border: "border-accent-hover",
    ring: "ring-accent-hover",
    shadow: "shadow-accent-hover",
  },
  {
    name: "background",
    bg: "bg-background",
    text: "text-background",
    border: "border-background",
    ring: "ring-background",
    shadow: "shadow-background",
  },
  {
    name: "blue",
    bg: "bg-blue",
    text: "text-blue",
    border: "border-blue",
    ring: "ring-blue",
    shadow: "shadow-blue",
  },
  {
    name: "blue-100",
    bg: "bg-blue-100",
    text: "text-blue-100",
    border: "border-blue-100",
    ring: "ring-blue-100",
    shadow: "shadow-blue-100",
  },
  {
    name: "blue-200",
    bg: "bg-blue-200",
    text: "text-blue-200",
    border: "border-blue-200",
    ring: "ring-blue-200",
    shadow: "shadow-blue-200",
  },
  {
    name: "blue-300",
    bg: "bg-blue-300",
    text: "text-blue-300",
    border: "border-blue-300",
    ring: "ring-blue-300",
    shadow: "shadow-blue-300",
  },
  {
    name: "blue-400",
    bg: "bg-blue-400",
    text: "text-blue-400",
    border: "border-blue-400",
    ring: "ring-blue-400",
    shadow: "shadow-blue-400",
  },
  {
    name: "blue-500",
    bg: "bg-blue-500",
    text: "text-blue-500",
    border: "border-blue-500",
    ring: "ring-blue-500",
    shadow: "shadow-blue-500",
  },
  {
    name: "blue-600",
    bg: "bg-blue-600",
    text: "text-blue-600",
    border: "border-blue-600",
    ring: "ring-blue-600",
    shadow: "shadow-blue-600",
  },
  {
    name: "blue-700",
    bg: "bg-blue-700",
    text: "text-blue-700",
    border: "border-blue-700",
    ring: "ring-blue-700",
    shadow: "shadow-blue-700",
  },
  {
    name: "blue-800",
    bg: "bg-blue-800",
    text: "text-blue-800",
    border: "border-blue-800",
    ring: "ring-blue-800",
    shadow: "shadow-blue-800",
  },
  {
    name: "blue-900",
    bg: "bg-blue-900",
    text: "text-blue-900",
    border: "border-blue-900",
    ring: "ring-blue-900",
    shadow: "shadow-blue-900",
  },
  {
    name: "blue-950",
    bg: "bg-blue-950",
    text: "text-blue-950",
    border: "border-blue-950",
    ring: "ring-blue-950",
    shadow: "shadow-blue-950",
  },
  {
    name: "border",
    bg: "bg-border",
    text: "text-border",
    border: "border-border",
    ring: "ring-border",
    shadow: "shadow-border",
  },
  {
    name: "card",
    bg: "bg-card",
    text: "text-card",
    border: "border-card",
    ring: "ring-card",
    shadow: "shadow-card",
  },
  {
    name: "card-foreground",
    bg: "bg-card-foreground",
    text: "text-card-foreground",
    border: "border-card-foreground",
    ring: "ring-card-foreground",
    shadow: "shadow-card-foreground",
  },
  {
    name: "chart-1",
    bg: "bg-chart-1",
    text: "text-chart-1",
    border: "border-chart-1",
    ring: "ring-chart-1",
    shadow: "shadow-chart-1",
  },
  {
    name: "chart-2",
    bg: "bg-chart-2",
    text: "text-chart-2",
    border: "border-chart-2",
    ring: "ring-chart-2",
    shadow: "shadow-chart-2",
  },
  {
    name: "chart-3",
    bg: "bg-chart-3",
    text: "text-chart-3",
    border: "border-chart-3",
    ring: "ring-chart-3",
    shadow: "shadow-chart-3",
  },
  {
    name: "chart-4",
    bg: "bg-chart-4",
    text: "text-chart-4",
    border: "border-chart-4",
    ring: "ring-chart-4",
    shadow: "shadow-chart-4",
  },
  {
    name: "chart-5",
    bg: "bg-chart-5",
    text: "text-chart-5",
    border: "border-chart-5",
    ring: "ring-chart-5",
    shadow: "shadow-chart-5",
  },
  {
    name: "core",
    bg: "bg-core",
    text: "text-core",
    border: "border-core",
    ring: "ring-core",
    shadow: "shadow-core",
  },
  {
    name: "crust",
    bg: "bg-crust",
    text: "text-crust",
    border: "border-crust",
    ring: "ring-crust",
    shadow: "shadow-crust",
  },
  {
    name: "destructive",
    bg: "bg-destructive",
    text: "text-destructive",
    border: "border-destructive",
    ring: "ring-destructive",
    shadow: "shadow-destructive",
  },
  {
    name: "destructive-foreground",
    bg: "bg-destructive-foreground",
    text: "text-destructive-foreground",
    border: "border-destructive-foreground",
    ring: "ring-destructive-foreground",
    shadow: "shadow-destructive-foreground",
  },
  {
    name: "destructive-hover",
    bg: "bg-destructive-hover",
    text: "text-destructive-hover",
    border: "border-destructive-hover",
    ring: "ring-destructive-hover",
    shadow: "shadow-destructive-hover",
  },
  {
    name: "flamingo",
    bg: "bg-flamingo",
    text: "text-flamingo",
    border: "border-flamingo",
    ring: "ring-flamingo",
    shadow: "shadow-flamingo",
  },
  {
    name: "flamingo-100",
    bg: "bg-flamingo-100",
    text: "text-flamingo-100",
    border: "border-flamingo-100",
    ring: "ring-flamingo-100",
    shadow: "shadow-flamingo-100",
  },
  {
    name: "flamingo-200",
    bg: "bg-flamingo-200",
    text: "text-flamingo-200",
    border: "border-flamingo-200",
    ring: "ring-flamingo-200",
    shadow: "shadow-flamingo-200",
  },
  {
    name: "flamingo-300",
    bg: "bg-flamingo-300",
    text: "text-flamingo-300",
    border: "border-flamingo-300",
    ring: "ring-flamingo-300",
    shadow: "shadow-flamingo-300",
  },
  {
    name: "flamingo-400",
    bg: "bg-flamingo-400",
    text: "text-flamingo-400",
    border: "border-flamingo-400",
    ring: "ring-flamingo-400",
    shadow: "shadow-flamingo-400",
  },
  {
    name: "flamingo-500",
    bg: "bg-flamingo-500",
    text: "text-flamingo-500",
    border: "border-flamingo-500",
    ring: "ring-flamingo-500",
    shadow: "shadow-flamingo-500",
  },
  {
    name: "flamingo-600",
    bg: "bg-flamingo-600",
    text: "text-flamingo-600",
    border: "border-flamingo-600",
    ring: "ring-flamingo-600",
    shadow: "shadow-flamingo-600",
  },
  {
    name: "flamingo-700",
    bg: "bg-flamingo-700",
    text: "text-flamingo-700",
    border: "border-flamingo-700",
    ring: "ring-flamingo-700",
    shadow: "shadow-flamingo-700",
  },
  {
    name: "flamingo-800",
    bg: "bg-flamingo-800",
    text: "text-flamingo-800",
    border: "border-flamingo-800",
    ring: "ring-flamingo-800",
    shadow: "shadow-flamingo-800",
  },
  {
    name: "flamingo-900",
    bg: "bg-flamingo-900",
    text: "text-flamingo-900",
    border: "border-flamingo-900",
    ring: "ring-flamingo-900",
    shadow: "shadow-flamingo-900",
  },
  {
    name: "flamingo-950",
    bg: "bg-flamingo-950",
    text: "text-flamingo-950",
    border: "border-flamingo-950",
    ring: "ring-flamingo-950",
    shadow: "shadow-flamingo-950",
  },
  {
    name: "foreground",
    bg: "bg-foreground",
    text: "text-foreground",
    border: "border-foreground",
    ring: "ring-foreground",
    shadow: "shadow-foreground",
  },
  {
    name: "green",
    bg: "bg-green",
    text: "text-green",
    border: "border-green",
    ring: "ring-green",
    shadow: "shadow-green",
  },
  {
    name: "green-100",
    bg: "bg-green-100",
    text: "text-green-100",
    border: "border-green-100",
    ring: "ring-green-100",
    shadow: "shadow-green-100",
  },
  {
    name: "green-200",
    bg: "bg-green-200",
    text: "text-green-200",
    border: "border-green-200",
    ring: "ring-green-200",
    shadow: "shadow-green-200",
  },
  {
    name: "green-300",
    bg: "bg-green-300",
    text: "text-green-300",
    border: "border-green-300",
    ring: "ring-green-300",
    shadow: "shadow-green-300",
  },
  {
    name: "green-400",
    bg: "bg-green-400",
    text: "text-green-400",
    border: "border-green-400",
    ring: "ring-green-400",
    shadow: "shadow-green-400",
  },
  {
    name: "green-500",
    bg: "bg-green-500",
    text: "text-green-500",
    border: "border-green-500",
    ring: "ring-green-500",
    shadow: "shadow-green-500",
  },
  {
    name: "green-600",
    bg: "bg-green-600",
    text: "text-green-600",
    border: "border-green-600",
    ring: "ring-green-600",
    shadow: "shadow-green-600",
  },
  {
    name: "green-700",
    bg: "bg-green-700",
    text: "text-green-700",
    border: "border-green-700",
    ring: "ring-green-700",
    shadow: "shadow-green-700",
  },
  {
    name: "green-800",
    bg: "bg-green-800",
    text: "text-green-800",
    border: "border-green-800",
    ring: "ring-green-800",
    shadow: "shadow-green-800",
  },
  {
    name: "green-900",
    bg: "bg-green-900",
    text: "text-green-900",
    border: "border-green-900",
    ring: "ring-green-900",
    shadow: "shadow-green-900",
  },
  {
    name: "green-950",
    bg: "bg-green-950",
    text: "text-green-950",
    border: "border-green-950",
    ring: "ring-green-950",
    shadow: "shadow-green-950",
  },
  {
    name: "input",
    bg: "bg-input",
    text: "text-input",
    border: "border-input",
    ring: "ring-input",
    shadow: "shadow-input",
  },
  {
    name: "input-disabled",
    bg: "bg-input-disabled",
    text: "text-input-disabled",
    border: "border-input-disabled",
    ring: "ring-input-disabled",
    shadow: "shadow-input-disabled",
  },
  {
    name: "input-focus",
    bg: "bg-input-focus",
    text: "text-input-focus",
    border: "border-input-focus",
    ring: "ring-input-focus",
    shadow: "shadow-input-focus",
  },
  {
    name: "input-foreground",
    bg: "bg-input-foreground",
    text: "text-input-foreground",
    border: "border-input-foreground",
    ring: "ring-input-foreground",
    shadow: "shadow-input-foreground",
  },
  {
    name: "input-invalid",
    bg: "bg-input-invalid",
    text: "text-input-invalid",
    border: "border-input-invalid",
    ring: "ring-input-invalid",
    shadow: "shadow-input-invalid",
  },
  {
    name: "input-placeholder",
    bg: "bg-input-placeholder",
    text: "text-input-placeholder",
    border: "border-input-placeholder",
    ring: "ring-input-placeholder",
    shadow: "shadow-input-placeholder",
  },
  {
    name: "input-readonly",
    bg: "bg-input-readonly",
    text: "text-input-readonly",
    border: "border-input-readonly",
    ring: "ring-input-readonly",
    shadow: "shadow-input-readonly",
  },
  {
    name: "input-required",
    bg: "bg-input-required",
    text: "text-input-required",
    border: "border-input-required",
    ring: "ring-input-required",
    shadow: "shadow-input-required",
  },
  {
    name: "input-valid",
    bg: "bg-input-valid",
    text: "text-input-valid",
    border: "border-input-valid",
    ring: "ring-input-valid",
    shadow: "shadow-input-valid",
  },
  {
    name: "lavender",
    bg: "bg-lavender",
    text: "text-lavender",
    border: "border-lavender",
    ring: "ring-lavender",
    shadow: "shadow-lavender",
  },
  {
    name: "lavender-100",
    bg: "bg-lavender-100",
    text: "text-lavender-100",
    border: "border-lavender-100",
    ring: "ring-lavender-100",
    shadow: "shadow-lavender-100",
  },
  {
    name: "lavender-200",
    bg: "bg-lavender-200",
    text: "text-lavender-200",
    border: "border-lavender-200",
    ring: "ring-lavender-200",
    shadow: "shadow-lavender-200",
  },
  {
    name: "lavender-300",
    bg: "bg-lavender-300",
    text: "text-lavender-300",
    border: "border-lavender-300",
    ring: "ring-lavender-300",
    shadow: "shadow-lavender-300",
  },
  {
    name: "lavender-400",
    bg: "bg-lavender-400",
    text: "text-lavender-400",
    border: "border-lavender-400",
    ring: "ring-lavender-400",
    shadow: "shadow-lavender-400",
  },
  {
    name: "lavender-500",
    bg: "bg-lavender-500",
    text: "text-lavender-500",
    border: "border-lavender-500",
    ring: "ring-lavender-500",
    shadow: "shadow-lavender-500",
  },
  {
    name: "lavender-600",
    bg: "bg-lavender-600",
    text: "text-lavender-600",
    border: "border-lavender-600",
    ring: "ring-lavender-600",
    shadow: "shadow-lavender-600",
  },
  {
    name: "lavender-700",
    bg: "bg-lavender-700",
    text: "text-lavender-700",
    border: "border-lavender-700",
    ring: "ring-lavender-700",
    shadow: "shadow-lavender-700",
  },
  {
    name: "lavender-800",
    bg: "bg-lavender-800",
    text: "text-lavender-800",
    border: "border-lavender-800",
    ring: "ring-lavender-800",
    shadow: "shadow-lavender-800",
  },
  {
    name: "lavender-900",
    bg: "bg-lavender-900",
    text: "text-lavender-900",
    border: "border-lavender-900",
    ring: "ring-lavender-900",
    shadow: "shadow-lavender-900",
  },
  {
    name: "lavender-950",
    bg: "bg-lavender-950",
    text: "text-lavender-950",
    border: "border-lavender-950",
    ring: "ring-lavender-950",
    shadow: "shadow-lavender-950",
  },
  {
    name: "mantle",
    bg: "bg-mantle",
    text: "text-mantle",
    border: "border-mantle",
    ring: "ring-mantle",
    shadow: "shadow-mantle",
  },
  {
    name: "maroon",
    bg: "bg-maroon",
    text: "text-maroon",
    border: "border-maroon",
    ring: "ring-maroon",
    shadow: "shadow-maroon",
  },
  {
    name: "maroon-100",
    bg: "bg-maroon-100",
    text: "text-maroon-100",
    border: "border-maroon-100",
    ring: "ring-maroon-100",
    shadow: "shadow-maroon-100",
  },
  {
    name: "maroon-200",
    bg: "bg-maroon-200",
    text: "text-maroon-200",
    border: "border-maroon-200",
    ring: "ring-maroon-200",
    shadow: "shadow-maroon-200",
  },
  {
    name: "maroon-300",
    bg: "bg-maroon-300",
    text: "text-maroon-300",
    border: "border-maroon-300",
    ring: "ring-maroon-300",
    shadow: "shadow-maroon-300",
  },
  {
    name: "maroon-400",
    bg: "bg-maroon-400",
    text: "text-maroon-400",
    border: "border-maroon-400",
    ring: "ring-maroon-400",
    shadow: "shadow-maroon-400",
  },
  {
    name: "maroon-500",
    bg: "bg-maroon-500",
    text: "text-maroon-500",
    border: "border-maroon-500",
    ring: "ring-maroon-500",
    shadow: "shadow-maroon-500",
  },
  {
    name: "maroon-600",
    bg: "bg-maroon-600",
    text: "text-maroon-600",
    border: "border-maroon-600",
    ring: "ring-maroon-600",
    shadow: "shadow-maroon-600",
  },
  {
    name: "maroon-700",
    bg: "bg-maroon-700",
    text: "text-maroon-700",
    border: "border-maroon-700",
    ring: "ring-maroon-700",
    shadow: "shadow-maroon-700",
  },
  {
    name: "maroon-800",
    bg: "bg-maroon-800",
    text: "text-maroon-800",
    border: "border-maroon-800",
    ring: "ring-maroon-800",
    shadow: "shadow-maroon-800",
  },
  {
    name: "maroon-900",
    bg: "bg-maroon-900",
    text: "text-maroon-900",
    border: "border-maroon-900",
    ring: "ring-maroon-900",
    shadow: "shadow-maroon-900",
  },
  {
    name: "maroon-950",
    bg: "bg-maroon-950",
    text: "text-maroon-950",
    border: "border-maroon-950",
    ring: "ring-maroon-950",
    shadow: "shadow-maroon-950",
  },
  {
    name: "mauve",
    bg: "bg-mauve",
    text: "text-mauve",
    border: "border-mauve",
    ring: "ring-mauve",
    shadow: "shadow-mauve",
  },
  {
    name: "mauve-100",
    bg: "bg-mauve-100",
    text: "text-mauve-100",
    border: "border-mauve-100",
    ring: "ring-mauve-100",
    shadow: "shadow-mauve-100",
  },
  {
    name: "mauve-200",
    bg: "bg-mauve-200",
    text: "text-mauve-200",
    border: "border-mauve-200",
    ring: "ring-mauve-200",
    shadow: "shadow-mauve-200",
  },
  {
    name: "mauve-300",
    bg: "bg-mauve-300",
    text: "text-mauve-300",
    border: "border-mauve-300",
    ring: "ring-mauve-300",
    shadow: "shadow-mauve-300",
  },
  {
    name: "mauve-400",
    bg: "bg-mauve-400",
    text: "text-mauve-400",
    border: "border-mauve-400",
    ring: "ring-mauve-400",
    shadow: "shadow-mauve-400",
  },
  {
    name: "mauve-500",
    bg: "bg-mauve-500",
    text: "text-mauve-500",
    border: "border-mauve-500",
    ring: "ring-mauve-500",
    shadow: "shadow-mauve-500",
  },
  {
    name: "mauve-600",
    bg: "bg-mauve-600",
    text: "text-mauve-600",
    border: "border-mauve-600",
    ring: "ring-mauve-600",
    shadow: "shadow-mauve-600",
  },
  {
    name: "mauve-700",
    bg: "bg-mauve-700",
    text: "text-mauve-700",
    border: "border-mauve-700",
    ring: "ring-mauve-700",
    shadow: "shadow-mauve-700",
  },
  {
    name: "mauve-800",
    bg: "bg-mauve-800",
    text: "text-mauve-800",
    border: "border-mauve-800",
    ring: "ring-mauve-800",
    shadow: "shadow-mauve-800",
  },
  {
    name: "mauve-900",
    bg: "bg-mauve-900",
    text: "text-mauve-900",
    border: "border-mauve-900",
    ring: "ring-mauve-900",
    shadow: "shadow-mauve-900",
  },
  {
    name: "mauve-950",
    bg: "bg-mauve-950",
    text: "text-mauve-950",
    border: "border-mauve-950",
    ring: "ring-mauve-950",
    shadow: "shadow-mauve-950",
  },
  {
    name: "muted",
    bg: "bg-muted",
    text: "text-muted",
    border: "border-muted",
    ring: "ring-muted",
    shadow: "shadow-muted",
  },
  {
    name: "muted-foreground",
    bg: "bg-muted-foreground",
    text: "text-muted-foreground",
    border: "border-muted-foreground",
    ring: "ring-muted-foreground",
    shadow: "shadow-muted-foreground",
  },
  {
    name: "overlay-0",
    bg: "bg-overlay-0",
    text: "text-overlay-0",
    border: "border-overlay-0",
    ring: "ring-overlay-0",
    shadow: "shadow-overlay-0",
  },
  {
    name: "overlay-1",
    bg: "bg-overlay-1",
    text: "text-overlay-1",
    border: "border-overlay-1",
    ring: "ring-overlay-1",
    shadow: "shadow-overlay-1",
  },
  {
    name: "overlay-2",
    bg: "bg-overlay-2",
    text: "text-overlay-2",
    border: "border-overlay-2",
    ring: "ring-overlay-2",
    shadow: "shadow-overlay-2",
  },
  {
    name: "peach",
    bg: "bg-peach",
    text: "text-peach",
    border: "border-peach",
    ring: "ring-peach",
    shadow: "shadow-peach",
  },
  {
    name: "peach-100",
    bg: "bg-peach-100",
    text: "text-peach-100",
    border: "border-peach-100",
    ring: "ring-peach-100",
    shadow: "shadow-peach-100",
  },
  {
    name: "peach-200",
    bg: "bg-peach-200",
    text: "text-peach-200",
    border: "border-peach-200",
    ring: "ring-peach-200",
    shadow: "shadow-peach-200",
  },
  {
    name: "peach-300",
    bg: "bg-peach-300",
    text: "text-peach-300",
    border: "border-peach-300",
    ring: "ring-peach-300",
    shadow: "shadow-peach-300",
  },
  {
    name: "peach-400",
    bg: "bg-peach-400",
    text: "text-peach-400",
    border: "border-peach-400",
    ring: "ring-peach-400",
    shadow: "shadow-peach-400",
  },
  {
    name: "peach-500",
    bg: "bg-peach-500",
    text: "text-peach-500",
    border: "border-peach-500",
    ring: "ring-peach-500",
    shadow: "shadow-peach-500",
  },
  {
    name: "peach-600",
    bg: "bg-peach-600",
    text: "text-peach-600",
    border: "border-peach-600",
    ring: "ring-peach-600",
    shadow: "shadow-peach-600",
  },
  {
    name: "peach-700",
    bg: "bg-peach-700",
    text: "text-peach-700",
    border: "border-peach-700",
    ring: "ring-peach-700",
    shadow: "shadow-peach-700",
  },
  {
    name: "peach-800",
    bg: "bg-peach-800",
    text: "text-peach-800",
    border: "border-peach-800",
    ring: "ring-peach-800",
    shadow: "shadow-peach-800",
  },
  {
    name: "peach-900",
    bg: "bg-peach-900",
    text: "text-peach-900",
    border: "border-peach-900",
    ring: "ring-peach-900",
    shadow: "shadow-peach-900",
  },
  {
    name: "peach-950",
    bg: "bg-peach-950",
    text: "text-peach-950",
    border: "border-peach-950",
    ring: "ring-peach-950",
    shadow: "shadow-peach-950",
  },
  {
    name: "pink",
    bg: "bg-pink",
    text: "text-pink",
    border: "border-pink",
    ring: "ring-pink",
    shadow: "shadow-pink",
  },
  {
    name: "pink-100",
    bg: "bg-pink-100",
    text: "text-pink-100",
    border: "border-pink-100",
    ring: "ring-pink-100",
    shadow: "shadow-pink-100",
  },
  {
    name: "pink-200",
    bg: "bg-pink-200",
    text: "text-pink-200",
    border: "border-pink-200",
    ring: "ring-pink-200",
    shadow: "shadow-pink-200",
  },
  {
    name: "pink-300",
    bg: "bg-pink-300",
    text: "text-pink-300",
    border: "border-pink-300",
    ring: "ring-pink-300",
    shadow: "shadow-pink-300",
  },
  {
    name: "pink-400",
    bg: "bg-pink-400",
    text: "text-pink-400",
    border: "border-pink-400",
    ring: "ring-pink-400",
    shadow: "shadow-pink-400",
  },
  {
    name: "pink-500",
    bg: "bg-pink-500",
    text: "text-pink-500",
    border: "border-pink-500",
    ring: "ring-pink-500",
    shadow: "shadow-pink-500",
  },
  {
    name: "pink-600",
    bg: "bg-pink-600",
    text: "text-pink-600",
    border: "border-pink-600",
    ring: "ring-pink-600",
    shadow: "shadow-pink-600",
  },
  {
    name: "pink-700",
    bg: "bg-pink-700",
    text: "text-pink-700",
    border: "border-pink-700",
    ring: "ring-pink-700",
    shadow: "shadow-pink-700",
  },
  {
    name: "pink-800",
    bg: "bg-pink-800",
    text: "text-pink-800",
    border: "border-pink-800",
    ring: "ring-pink-800",
    shadow: "shadow-pink-800",
  },
  {
    name: "pink-900",
    bg: "bg-pink-900",
    text: "text-pink-900",
    border: "border-pink-900",
    ring: "ring-pink-900",
    shadow: "shadow-pink-900",
  },
  {
    name: "pink-950",
    bg: "bg-pink-950",
    text: "text-pink-950",
    border: "border-pink-950",
    ring: "ring-pink-950",
    shadow: "shadow-pink-950",
  },
  {
    name: "popover",
    bg: "bg-popover",
    text: "text-popover",
    border: "border-popover",
    ring: "ring-popover",
    shadow: "shadow-popover",
  },
  {
    name: "popover-foreground",
    bg: "bg-popover-foreground",
    text: "text-popover-foreground",
    border: "border-popover-foreground",
    ring: "ring-popover-foreground",
    shadow: "shadow-popover-foreground",
  },
  {
    name: "primary",
    bg: "bg-primary",
    text: "text-primary",
    border: "border-primary",
    ring: "ring-primary",
    shadow: "shadow-primary",
  },
  {
    name: "primary-foreground",
    bg: "bg-primary-foreground",
    text: "text-primary-foreground",
    border: "border-primary-foreground",
    ring: "ring-primary-foreground",
    shadow: "shadow-primary-foreground",
  },
  {
    name: "primary-hover",
    bg: "bg-primary-hover",
    text: "text-primary-hover",
    border: "border-primary-hover",
    ring: "ring-primary-hover",
    shadow: "shadow-primary-hover",
  },
  {
    name: "red",
    bg: "bg-red",
    text: "text-red",
    border: "border-red",
    ring: "ring-red",
    shadow: "shadow-red",
  },
  {
    name: "red-100",
    bg: "bg-red-100",
    text: "text-red-100",
    border: "border-red-100",
    ring: "ring-red-100",
    shadow: "shadow-red-100",
  },
  {
    name: "red-200",
    bg: "bg-red-200",
    text: "text-red-200",
    border: "border-red-200",
    ring: "ring-red-200",
    shadow: "shadow-red-200",
  },
  {
    name: "red-300",
    bg: "bg-red-300",
    text: "text-red-300",
    border: "border-red-300",
    ring: "ring-red-300",
    shadow: "shadow-red-300",
  },
  {
    name: "red-400",
    bg: "bg-red-400",
    text: "text-red-400",
    border: "border-red-400",
    ring: "ring-red-400",
    shadow: "shadow-red-400",
  },
  {
    name: "red-500",
    bg: "bg-red-500",
    text: "text-red-500",
    border: "border-red-500",
    ring: "ring-red-500",
    shadow: "shadow-red-500",
  },
  {
    name: "red-600",
    bg: "bg-red-600",
    text: "text-red-600",
    border: "border-red-600",
    ring: "ring-red-600",
    shadow: "shadow-red-600",
  },
  {
    name: "red-700",
    bg: "bg-red-700",
    text: "text-red-700",
    border: "border-red-700",
    ring: "ring-red-700",
    shadow: "shadow-red-700",
  },
  {
    name: "red-800",
    bg: "bg-red-800",
    text: "text-red-800",
    border: "border-red-800",
    ring: "ring-red-800",
    shadow: "shadow-red-800",
  },
  {
    name: "red-900",
    bg: "bg-red-900",
    text: "text-red-900",
    border: "border-red-900",
    ring: "ring-red-900",
    shadow: "shadow-red-900",
  },
  {
    name: "red-950",
    bg: "bg-red-950",
    text: "text-red-950",
    border: "border-red-950",
    ring: "ring-red-950",
    shadow: "shadow-red-950",
  },
  {
    name: "ring",
    bg: "bg-ring",
    text: "text-ring",
    border: "border-ring",
    ring: "ring-ring",
    shadow: "shadow-ring",
  },
  {
    name: "rosewater",
    bg: "bg-rosewater",
    text: "text-rosewater",
    border: "border-rosewater",
    ring: "ring-rosewater",
    shadow: "shadow-rosewater",
  },
  {
    name: "rosewater-100",
    bg: "bg-rosewater-100",
    text: "text-rosewater-100",
    border: "border-rosewater-100",
    ring: "ring-rosewater-100",
    shadow: "shadow-rosewater-100",
  },
  {
    name: "rosewater-200",
    bg: "bg-rosewater-200",
    text: "text-rosewater-200",
    border: "border-rosewater-200",
    ring: "ring-rosewater-200",
    shadow: "shadow-rosewater-200",
  },
  {
    name: "rosewater-300",
    bg: "bg-rosewater-300",
    text: "text-rosewater-300",
    border: "border-rosewater-300",
    ring: "ring-rosewater-300",
    shadow: "shadow-rosewater-300",
  },
  {
    name: "rosewater-400",
    bg: "bg-rosewater-400",
    text: "text-rosewater-400",
    border: "border-rosewater-400",
    ring: "ring-rosewater-400",
    shadow: "shadow-rosewater-400",
  },
  {
    name: "rosewater-500",
    bg: "bg-rosewater-500",
    text: "text-rosewater-500",
    border: "border-rosewater-500",
    ring: "ring-rosewater-500",
    shadow: "shadow-rosewater-500",
  },
  {
    name: "rosewater-600",
    bg: "bg-rosewater-600",
    text: "text-rosewater-600",
    border: "border-rosewater-600",
    ring: "ring-rosewater-600",
    shadow: "shadow-rosewater-600",
  },
  {
    name: "rosewater-700",
    bg: "bg-rosewater-700",
    text: "text-rosewater-700",
    border: "border-rosewater-700",
    ring: "ring-rosewater-700",
    shadow: "shadow-rosewater-700",
  },
  {
    name: "rosewater-800",
    bg: "bg-rosewater-800",
    text: "text-rosewater-800",
    border: "border-rosewater-800",
    ring: "ring-rosewater-800",
    shadow: "shadow-rosewater-800",
  },
  {
    name: "rosewater-900",
    bg: "bg-rosewater-900",
    text: "text-rosewater-900",
    border: "border-rosewater-900",
    ring: "ring-rosewater-900",
    shadow: "shadow-rosewater-900",
  },
  {
    name: "rosewater-950",
    bg: "bg-rosewater-950",
    text: "text-rosewater-950",
    border: "border-rosewater-950",
    ring: "ring-rosewater-950",
    shadow: "shadow-rosewater-950",
  },
  {
    name: "sapphire",
    bg: "bg-sapphire",
    text: "text-sapphire",
    border: "border-sapphire",
    ring: "ring-sapphire",
    shadow: "shadow-sapphire",
  },
  {
    name: "sapphire-100",
    bg: "bg-sapphire-100",
    text: "text-sapphire-100",
    border: "border-sapphire-100",
    ring: "ring-sapphire-100",
    shadow: "shadow-sapphire-100",
  },
  {
    name: "sapphire-200",
    bg: "bg-sapphire-200",
    text: "text-sapphire-200",
    border: "border-sapphire-200",
    ring: "ring-sapphire-200",
    shadow: "shadow-sapphire-200",
  },
  {
    name: "sapphire-300",
    bg: "bg-sapphire-300",
    text: "text-sapphire-300",
    border: "border-sapphire-300",
    ring: "ring-sapphire-300",
    shadow: "shadow-sapphire-300",
  },
  {
    name: "sapphire-400",
    bg: "bg-sapphire-400",
    text: "text-sapphire-400",
    border: "border-sapphire-400",
    ring: "ring-sapphire-400",
    shadow: "shadow-sapphire-400",
  },
  {
    name: "sapphire-500",
    bg: "bg-sapphire-500",
    text: "text-sapphire-500",
    border: "border-sapphire-500",
    ring: "ring-sapphire-500",
    shadow: "shadow-sapphire-500",
  },
  {
    name: "sapphire-600",
    bg: "bg-sapphire-600",
    text: "text-sapphire-600",
    border: "border-sapphire-600",
    ring: "ring-sapphire-600",
    shadow: "shadow-sapphire-600",
  },
  {
    name: "sapphire-700",
    bg: "bg-sapphire-700",
    text: "text-sapphire-700",
    border: "border-sapphire-700",
    ring: "ring-sapphire-700",
    shadow: "shadow-sapphire-700",
  },
  {
    name: "sapphire-800",
    bg: "bg-sapphire-800",
    text: "text-sapphire-800",
    border: "border-sapphire-800",
    ring: "ring-sapphire-800",
    shadow: "shadow-sapphire-800",
  },
  {
    name: "sapphire-900",
    bg: "bg-sapphire-900",
    text: "text-sapphire-900",
    border: "border-sapphire-900",
    ring: "ring-sapphire-900",
    shadow: "shadow-sapphire-900",
  },
  {
    name: "sapphire-950",
    bg: "bg-sapphire-950",
    text: "text-sapphire-950",
    border: "border-sapphire-950",
    ring: "ring-sapphire-950",
    shadow: "shadow-sapphire-950",
  },
  {
    name: "secondary",
    bg: "bg-secondary",
    text: "text-secondary",
    border: "border-secondary",
    ring: "ring-secondary",
    shadow: "shadow-secondary",
  },
  {
    name: "secondary-foreground",
    bg: "bg-secondary-foreground",
    text: "text-secondary-foreground",
    border: "border-secondary-foreground",
    ring: "ring-secondary-foreground",
    shadow: "shadow-secondary-foreground",
  },
  {
    name: "secondary-hover",
    bg: "bg-secondary-hover",
    text: "text-secondary-hover",
    border: "border-secondary-hover",
    ring: "ring-secondary-hover",
    shadow: "shadow-secondary-hover",
  },
  {
    name: "sidebar",
    bg: "bg-sidebar",
    text: "text-sidebar",
    border: "border-sidebar",
    ring: "ring-sidebar",
    shadow: "shadow-sidebar",
  },
  {
    name: "sidebar-accent",
    bg: "bg-sidebar-accent",
    text: "text-sidebar-accent",
    border: "border-sidebar-accent",
    ring: "ring-sidebar-accent",
    shadow: "shadow-sidebar-accent",
  },
  {
    name: "sidebar-accent-foreground",
    bg: "bg-sidebar-accent-foreground",
    text: "text-sidebar-accent-foreground",
    border: "border-sidebar-accent-foreground",
    ring: "ring-sidebar-accent-foreground",
    shadow: "shadow-sidebar-accent-foreground",
  },
  {
    name: "sidebar-border",
    bg: "bg-sidebar-border",
    text: "text-sidebar-border",
    border: "border-sidebar-border",
    ring: "ring-sidebar-border",
    shadow: "shadow-sidebar-border",
  },
  {
    name: "sidebar-foreground",
    bg: "bg-sidebar-foreground",
    text: "text-sidebar-foreground",
    border: "border-sidebar-foreground",
    ring: "ring-sidebar-foreground",
    shadow: "shadow-sidebar-foreground",
  },
  {
    name: "sidebar-primary",
    bg: "bg-sidebar-primary",
    text: "text-sidebar-primary",
    border: "border-sidebar-primary",
    ring: "ring-sidebar-primary",
    shadow: "shadow-sidebar-primary",
  },
  {
    name: "sidebar-primary-foreground",
    bg: "bg-sidebar-primary-foreground",
    text: "text-sidebar-primary-foreground",
    border: "border-sidebar-primary-foreground",
    ring: "ring-sidebar-primary-foreground",
    shadow: "shadow-sidebar-primary-foreground",
  },
  {
    name: "sidebar-ring",
    bg: "bg-sidebar-ring",
    text: "text-sidebar-ring",
    border: "border-sidebar-ring",
    ring: "ring-sidebar-ring",
    shadow: "shadow-sidebar-ring",
  },
  {
    name: "sky",
    bg: "bg-sky",
    text: "text-sky",
    border: "border-sky",
    ring: "ring-sky",
    shadow: "shadow-sky",
  },
  {
    name: "sky-100",
    bg: "bg-sky-100",
    text: "text-sky-100",
    border: "border-sky-100",
    ring: "ring-sky-100",
    shadow: "shadow-sky-100",
  },
  {
    name: "sky-200",
    bg: "bg-sky-200",
    text: "text-sky-200",
    border: "border-sky-200",
    ring: "ring-sky-200",
    shadow: "shadow-sky-200",
  },
  {
    name: "sky-300",
    bg: "bg-sky-300",
    text: "text-sky-300",
    border: "border-sky-300",
    ring: "ring-sky-300",
    shadow: "shadow-sky-300",
  },
  {
    name: "sky-400",
    bg: "bg-sky-400",
    text: "text-sky-400",
    border: "border-sky-400",
    ring: "ring-sky-400",
    shadow: "shadow-sky-400",
  },
  {
    name: "sky-500",
    bg: "bg-sky-500",
    text: "text-sky-500",
    border: "border-sky-500",
    ring: "ring-sky-500",
    shadow: "shadow-sky-500",
  },
  {
    name: "sky-600",
    bg: "bg-sky-600",
    text: "text-sky-600",
    border: "border-sky-600",
    ring: "ring-sky-600",
    shadow: "shadow-sky-600",
  },
  {
    name: "sky-700",
    bg: "bg-sky-700",
    text: "text-sky-700",
    border: "border-sky-700",
    ring: "ring-sky-700",
    shadow: "shadow-sky-700",
  },
  {
    name: "sky-800",
    bg: "bg-sky-800",
    text: "text-sky-800",
    border: "border-sky-800",
    ring: "ring-sky-800",
    shadow: "shadow-sky-800",
  },
  {
    name: "sky-900",
    bg: "bg-sky-900",
    text: "text-sky-900",
    border: "border-sky-900",
    ring: "ring-sky-900",
    shadow: "shadow-sky-900",
  },
  {
    name: "sky-950",
    bg: "bg-sky-950",
    text: "text-sky-950",
    border: "border-sky-950",
    ring: "ring-sky-950",
    shadow: "shadow-sky-950",
  },
  {
    name: "subtext-0",
    bg: "bg-subtext-0",
    text: "text-subtext-0",
    border: "border-subtext-0",
    ring: "ring-subtext-0",
    shadow: "shadow-subtext-0",
  },
  {
    name: "subtext-1",
    bg: "bg-subtext-1",
    text: "text-subtext-1",
    border: "border-subtext-1",
    ring: "ring-subtext-1",
    shadow: "shadow-subtext-1",
  },
  {
    name: "success",
    bg: "bg-success",
    text: "text-success",
    border: "border-success",
    ring: "ring-success",
    shadow: "shadow-success",
  },
  {
    name: "success-foreground",
    bg: "bg-success-foreground",
    text: "text-success-foreground",
    border: "border-success-foreground",
    ring: "ring-success-foreground",
    shadow: "shadow-success-foreground",
  },
  {
    name: "success-hover",
    bg: "bg-success-hover",
    text: "text-success-hover",
    border: "border-success-hover",
    ring: "ring-success-hover",
    shadow: "shadow-success-hover",
  },
  {
    name: "surface-0",
    bg: "bg-surface-0",
    text: "text-surface-0",
    border: "border-surface-0",
    ring: "ring-surface-0",
    shadow: "shadow-surface-0",
  },
  {
    name: "surface-1",
    bg: "bg-surface-1",
    text: "text-surface-1",
    border: "border-surface-1",
    ring: "ring-surface-1",
    shadow: "shadow-surface-1",
  },
  {
    name: "surface-2",
    bg: "bg-surface-2",
    text: "text-surface-2",
    border: "border-surface-2",
    ring: "ring-surface-2",
    shadow: "shadow-surface-2",
  },
  {
    name: "teal",
    bg: "bg-teal",
    text: "text-teal",
    border: "border-teal",
    ring: "ring-teal",
    shadow: "shadow-teal",
  },
  {
    name: "teal-100",
    bg: "bg-teal-100",
    text: "text-teal-100",
    border: "border-teal-100",
    ring: "ring-teal-100",
    shadow: "shadow-teal-100",
  },
  {
    name: "teal-200",
    bg: "bg-teal-200",
    text: "text-teal-200",
    border: "border-teal-200",
    ring: "ring-teal-200",
    shadow: "shadow-teal-200",
  },
  {
    name: "teal-300",
    bg: "bg-teal-300",
    text: "text-teal-300",
    border: "border-teal-300",
    ring: "ring-teal-300",
    shadow: "shadow-teal-300",
  },
  {
    name: "teal-400",
    bg: "bg-teal-400",
    text: "text-teal-400",
    border: "border-teal-400",
    ring: "ring-teal-400",
    shadow: "shadow-teal-400",
  },
  {
    name: "teal-500",
    bg: "bg-teal-500",
    text: "text-teal-500",
    border: "border-teal-500",
    ring: "ring-teal-500",
    shadow: "shadow-teal-500",
  },
  {
    name: "teal-600",
    bg: "bg-teal-600",
    text: "text-teal-600",
    border: "border-teal-600",
    ring: "ring-teal-600",
    shadow: "shadow-teal-600",
  },
  {
    name: "teal-700",
    bg: "bg-teal-700",
    text: "text-teal-700",
    border: "border-teal-700",
    ring: "ring-teal-700",
    shadow: "shadow-teal-700",
  },
  {
    name: "teal-800",
    bg: "bg-teal-800",
    text: "text-teal-800",
    border: "border-teal-800",
    ring: "ring-teal-800",
    shadow: "shadow-teal-800",
  },
  {
    name: "teal-900",
    bg: "bg-teal-900",
    text: "text-teal-900",
    border: "border-teal-900",
    ring: "ring-teal-900",
    shadow: "shadow-teal-900",
  },
  {
    name: "teal-950",
    bg: "bg-teal-950",
    text: "text-teal-950",
    border: "border-teal-950",
    ring: "ring-teal-950",
    shadow: "shadow-teal-950",
  },
  {
    name: "text",
    bg: "bg-text",
    text: "text-text",
    border: "border-text",
    ring: "ring-text",
    shadow: "shadow-text",
  },
  {
    name: "yellow",
    bg: "bg-yellow",
    text: "text-yellow",
    border: "border-yellow",
    ring: "ring-yellow",
    shadow: "shadow-yellow",
  },
  {
    name: "yellow-100",
    bg: "bg-yellow-100",
    text: "text-yellow-100",
    border: "border-yellow-100",
    ring: "ring-yellow-100",
    shadow: "shadow-yellow-100",
  },
  {
    name: "yellow-200",
    bg: "bg-yellow-200",
    text: "text-yellow-200",
    border: "border-yellow-200",
    ring: "ring-yellow-200",
    shadow: "shadow-yellow-200",
  },
  {
    name: "yellow-300",
    bg: "bg-yellow-300",
    text: "text-yellow-300",
    border: "border-yellow-300",
    ring: "ring-yellow-300",
    shadow: "shadow-yellow-300",
  },
  {
    name: "yellow-400",
    bg: "bg-yellow-400",
    text: "text-yellow-400",
    border: "border-yellow-400",
    ring: "ring-yellow-400",
    shadow: "shadow-yellow-400",
  },
  {
    name: "yellow-500",
    bg: "bg-yellow-500",
    text: "text-yellow-500",
    border: "border-yellow-500",
    ring: "ring-yellow-500",
    shadow: "shadow-yellow-500",
  },
  {
    name: "yellow-600",
    bg: "bg-yellow-600",
    text: "text-yellow-600",
    border: "border-yellow-600",
    ring: "ring-yellow-600",
    shadow: "shadow-yellow-600",
  },
  {
    name: "yellow-700",
    bg: "bg-yellow-700",
    text: "text-yellow-700",
    border: "border-yellow-700",
    ring: "ring-yellow-700",
    shadow: "shadow-yellow-700",
  },
  {
    name: "yellow-800",
    bg: "bg-yellow-800",
    text: "text-yellow-800",
    border: "border-yellow-800",
    ring: "ring-yellow-800",
    shadow: "shadow-yellow-800",
  },
  {
    name: "yellow-900",
    bg: "bg-yellow-900",
    text: "text-yellow-900",
    border: "border-yellow-900",
    ring: "ring-yellow-900",
    shadow: "shadow-yellow-900",
  },
  {
    name: "yellow-950",
    bg: "bg-yellow-950",
    text: "text-yellow-950",
    border: "border-yellow-950",
    ring: "ring-yellow-950",
    shadow: "shadow-yellow-950",
  },
] as const;

/** Text size utilities backed by the custom golden-ratio type scale. */
export const textSizeClasses = [
  "text-xs",
  "text-sm",
  "text-md",
  "text-core",
  "text-lg",
  "text-xl",
  "text-2x",
  "text-3x",
  "text-4x",
  "text-5x",
  "text-6x",
  "text-7x",
  "text-8x",
  "text-9x",
  "text-min",
  "text-max",
] as const;

/** Font-family utilities available in the typography token matrix. */
export const fontClasses = ["font-sans", "font-serif", "font-mono"] as const;

/** Spacing utility groups for padding, margin, gap, space, and inset demonstrations. */
export const spacingClasses = [
  {
    name: "xs",
    padding: ["p-xs", "px-xs", "py-xs", "ps-xs", "pe-xs", "pt-xs", "pr-xs", "pb-xs", "pl-xs"],
    margin: ["m-xs", "mx-xs", "my-xs", "ms-xs", "me-xs", "mt-xs", "mr-xs", "mb-xs", "ml-xs"],
    gap: ["gap-xs", "gap-x-xs", "gap-y-xs"],
    space: ["space-x-xs", "space-y-xs"],
    inset: [
      "inset-xs",
      "inset-x-xs",
      "inset-y-xs",
      "start-xs",
      "end-xs",
      "top-xs",
      "right-xs",
      "bottom-xs",
      "left-xs",
    ],
  },
  {
    name: "sm",
    padding: ["p-sm", "px-sm", "py-sm", "ps-sm", "pe-sm", "pt-sm", "pr-sm", "pb-sm", "pl-sm"],
    margin: ["m-sm", "mx-sm", "my-sm", "ms-sm", "me-sm", "mt-sm", "mr-sm", "mb-sm", "ml-sm"],
    gap: ["gap-sm", "gap-x-sm", "gap-y-sm"],
    space: ["space-x-sm", "space-y-sm"],
    inset: [
      "inset-sm",
      "inset-x-sm",
      "inset-y-sm",
      "start-sm",
      "end-sm",
      "top-sm",
      "right-sm",
      "bottom-sm",
      "left-sm",
    ],
  },
  {
    name: "base",
    padding: [
      "p-base",
      "px-base",
      "py-base",
      "ps-base",
      "pe-base",
      "pt-base",
      "pr-base",
      "pb-base",
      "pl-base",
    ],
    margin: [
      "m-base",
      "mx-base",
      "my-base",
      "ms-base",
      "me-base",
      "mt-base",
      "mr-base",
      "mb-base",
      "ml-base",
    ],
    gap: ["gap-base", "gap-x-base", "gap-y-base"],
    space: ["space-x-base", "space-y-base"],
    inset: [
      "inset-base",
      "inset-x-base",
      "inset-y-base",
      "start-base",
      "end-base",
      "top-base",
      "right-base",
      "bottom-base",
      "left-base",
    ],
  },
  {
    name: "md",
    padding: ["p-md", "px-md", "py-md", "ps-md", "pe-md", "pt-md", "pr-md", "pb-md", "pl-md"],
    margin: ["m-md", "mx-md", "my-md", "ms-md", "me-md", "mt-md", "mr-md", "mb-md", "ml-md"],
    gap: ["gap-md", "gap-x-md", "gap-y-md"],
    space: ["space-x-md", "space-y-md"],
    inset: [
      "inset-md",
      "inset-x-md",
      "inset-y-md",
      "start-md",
      "end-md",
      "top-md",
      "right-md",
      "bottom-md",
      "left-md",
    ],
  },
  {
    name: "lg",
    padding: ["p-lg", "px-lg", "py-lg", "ps-lg", "pe-lg", "pt-lg", "pr-lg", "pb-lg", "pl-lg"],
    margin: ["m-lg", "mx-lg", "my-lg", "ms-lg", "me-lg", "mt-lg", "mr-lg", "mb-lg", "ml-lg"],
    gap: ["gap-lg", "gap-x-lg", "gap-y-lg"],
    space: ["space-x-lg", "space-y-lg"],
    inset: [
      "inset-lg",
      "inset-x-lg",
      "inset-y-lg",
      "start-lg",
      "end-lg",
      "top-lg",
      "right-lg",
      "bottom-lg",
      "left-lg",
    ],
  },
  {
    name: "xl",
    padding: ["p-xl", "px-xl", "py-xl", "ps-xl", "pe-xl", "pt-xl", "pr-xl", "pb-xl", "pl-xl"],
    margin: ["m-xl", "mx-xl", "my-xl", "ms-xl", "me-xl", "mt-xl", "mr-xl", "mb-xl", "ml-xl"],
    gap: ["gap-xl", "gap-x-xl", "gap-y-xl"],
    space: ["space-x-xl", "space-y-xl"],
    inset: [
      "inset-xl",
      "inset-x-xl",
      "inset-y-xl",
      "start-xl",
      "end-xl",
      "top-xl",
      "right-xl",
      "bottom-xl",
      "left-xl",
    ],
  },
  {
    name: "2x",
    padding: ["p-2x", "px-2x", "py-2x", "ps-2x", "pe-2x", "pt-2x", "pr-2x", "pb-2x", "pl-2x"],
    margin: ["m-2x", "mx-2x", "my-2x", "ms-2x", "me-2x", "mt-2x", "mr-2x", "mb-2x", "ml-2x"],
    gap: ["gap-2x", "gap-x-2x", "gap-y-2x"],
    space: ["space-x-2x", "space-y-2x"],
    inset: [
      "inset-2x",
      "inset-x-2x",
      "inset-y-2x",
      "start-2x",
      "end-2x",
      "top-2x",
      "right-2x",
      "bottom-2x",
      "left-2x",
    ],
  },
  {
    name: "3x",
    padding: ["p-3x", "px-3x", "py-3x", "ps-3x", "pe-3x", "pt-3x", "pr-3x", "pb-3x", "pl-3x"],
    margin: ["m-3x", "mx-3x", "my-3x", "ms-3x", "me-3x", "mt-3x", "mr-3x", "mb-3x", "ml-3x"],
    gap: ["gap-3x", "gap-x-3x", "gap-y-3x"],
    space: ["space-x-3x", "space-y-3x"],
    inset: [
      "inset-3x",
      "inset-x-3x",
      "inset-y-3x",
      "start-3x",
      "end-3x",
      "top-3x",
      "right-3x",
      "bottom-3x",
      "left-3x",
    ],
  },
  {
    name: "4x",
    padding: ["p-4x", "px-4x", "py-4x", "ps-4x", "pe-4x", "pt-4x", "pr-4x", "pb-4x", "pl-4x"],
    margin: ["m-4x", "mx-4x", "my-4x", "ms-4x", "me-4x", "mt-4x", "mr-4x", "mb-4x", "ml-4x"],
    gap: ["gap-4x", "gap-x-4x", "gap-y-4x"],
    space: ["space-x-4x", "space-y-4x"],
    inset: [
      "inset-4x",
      "inset-x-4x",
      "inset-y-4x",
      "start-4x",
      "end-4x",
      "top-4x",
      "right-4x",
      "bottom-4x",
      "left-4x",
    ],
  },
  {
    name: "5x",
    padding: ["p-5x", "px-5x", "py-5x", "ps-5x", "pe-5x", "pt-5x", "pr-5x", "pb-5x", "pl-5x"],
    margin: ["m-5x", "mx-5x", "my-5x", "ms-5x", "me-5x", "mt-5x", "mr-5x", "mb-5x", "ml-5x"],
    gap: ["gap-5x", "gap-x-5x", "gap-y-5x"],
    space: ["space-x-5x", "space-y-5x"],
    inset: [
      "inset-5x",
      "inset-x-5x",
      "inset-y-5x",
      "start-5x",
      "end-5x",
      "top-5x",
      "right-5x",
      "bottom-5x",
      "left-5x",
    ],
  },
  {
    name: "6x",
    padding: ["p-6x", "px-6x", "py-6x", "ps-6x", "pe-6x", "pt-6x", "pr-6x", "pb-6x", "pl-6x"],
    margin: ["m-6x", "mx-6x", "my-6x", "ms-6x", "me-6x", "mt-6x", "mr-6x", "mb-6x", "ml-6x"],
    gap: ["gap-6x", "gap-x-6x", "gap-y-6x"],
    space: ["space-x-6x", "space-y-6x"],
    inset: [
      "inset-6x",
      "inset-x-6x",
      "inset-y-6x",
      "start-6x",
      "end-6x",
      "top-6x",
      "right-6x",
      "bottom-6x",
      "left-6x",
    ],
  },
  {
    name: "7x",
    padding: ["p-7x", "px-7x", "py-7x", "ps-7x", "pe-7x", "pt-7x", "pr-7x", "pb-7x", "pl-7x"],
    margin: ["m-7x", "mx-7x", "my-7x", "ms-7x", "me-7x", "mt-7x", "mr-7x", "mb-7x", "ml-7x"],
    gap: ["gap-7x", "gap-x-7x", "gap-y-7x"],
    space: ["space-x-7x", "space-y-7x"],
    inset: [
      "inset-7x",
      "inset-x-7x",
      "inset-y-7x",
      "start-7x",
      "end-7x",
      "top-7x",
      "right-7x",
      "bottom-7x",
      "left-7x",
    ],
  },
  {
    name: "8x",
    padding: ["p-8x", "px-8x", "py-8x", "ps-8x", "pe-8x", "pt-8x", "pr-8x", "pb-8x", "pl-8x"],
    margin: ["m-8x", "mx-8x", "my-8x", "ms-8x", "me-8x", "mt-8x", "mr-8x", "mb-8x", "ml-8x"],
    gap: ["gap-8x", "gap-x-8x", "gap-y-8x"],
    space: ["space-x-8x", "space-y-8x"],
    inset: [
      "inset-8x",
      "inset-x-8x",
      "inset-y-8x",
      "start-8x",
      "end-8x",
      "top-8x",
      "right-8x",
      "bottom-8x",
      "left-8x",
    ],
  },
  {
    name: "9x",
    padding: ["p-9x", "px-9x", "py-9x", "ps-9x", "pe-9x", "pt-9x", "pr-9x", "pb-9x", "pl-9x"],
    margin: ["m-9x", "mx-9x", "my-9x", "ms-9x", "me-9x", "mt-9x", "mr-9x", "mb-9x", "ml-9x"],
    gap: ["gap-9x", "gap-x-9x", "gap-y-9x"],
    space: ["space-x-9x", "space-y-9x"],
    inset: [
      "inset-9x",
      "inset-x-9x",
      "inset-y-9x",
      "start-9x",
      "end-9x",
      "top-9x",
      "right-9x",
      "bottom-9x",
      "left-9x",
    ],
  },
  {
    name: "gw",
    padding: ["p-gw", "px-gw", "py-gw", "ps-gw", "pe-gw", "pt-gw", "pr-gw", "pb-gw", "pl-gw"],
    margin: ["m-gw", "mx-gw", "my-gw", "ms-gw", "me-gw", "mt-gw", "mr-gw", "mb-gw", "ml-gw"],
    gap: ["gap-gw", "gap-x-gw", "gap-y-gw"],
    space: ["space-x-gw", "space-y-gw"],
    inset: [
      "inset-gw",
      "inset-x-gw",
      "inset-y-gw",
      "start-gw",
      "end-gw",
      "top-gw",
      "right-gw",
      "bottom-gw",
      "left-gw",
    ],
  },
  {
    name: "gn",
    padding: ["p-gn", "px-gn", "py-gn", "ps-gn", "pe-gn", "pt-gn", "pr-gn", "pb-gn", "pl-gn"],
    margin: ["m-gn", "mx-gn", "my-gn", "ms-gn", "me-gn", "mt-gn", "mr-gn", "mb-gn", "ml-gn"],
    gap: ["gap-gn", "gap-x-gn", "gap-y-gn"],
    space: ["space-x-gn", "space-y-gn"],
    inset: [
      "inset-gn",
      "inset-x-gn",
      "inset-y-gn",
      "start-gn",
      "end-gn",
      "top-gn",
      "right-gn",
      "bottom-gn",
      "left-gn",
    ],
  },
  {
    name: "gn-2x",
    padding: [
      "p-gn-2x",
      "px-gn-2x",
      "py-gn-2x",
      "ps-gn-2x",
      "pe-gn-2x",
      "pt-gn-2x",
      "pr-gn-2x",
      "pb-gn-2x",
      "pl-gn-2x",
    ],
    margin: [
      "m-gn-2x",
      "mx-gn-2x",
      "my-gn-2x",
      "ms-gn-2x",
      "me-gn-2x",
      "mt-gn-2x",
      "mr-gn-2x",
      "mb-gn-2x",
      "ml-gn-2x",
    ],
    gap: ["gap-gn-2x", "gap-x-gn-2x", "gap-y-gn-2x"],
    space: ["space-x-gn-2x", "space-y-gn-2x"],
    inset: [
      "inset-gn-2x",
      "inset-x-gn-2x",
      "inset-y-gn-2x",
      "start-gn-2x",
      "end-gn-2x",
      "top-gn-2x",
      "right-gn-2x",
      "bottom-gn-2x",
      "left-gn-2x",
    ],
  },
  {
    name: "gn-1/2",
    padding: [
      "p-gn-1/2",
      "px-gn-1/2",
      "py-gn-1/2",
      "ps-gn-1/2",
      "pe-gn-1/2",
      "pt-gn-1/2",
      "pr-gn-1/2",
      "pb-gn-1/2",
      "pl-gn-1/2",
    ],
    margin: [
      "m-gn-1/2",
      "mx-gn-1/2",
      "my-gn-1/2",
      "ms-gn-1/2",
      "me-gn-1/2",
      "mt-gn-1/2",
      "mr-gn-1/2",
      "mb-gn-1/2",
      "ml-gn-1/2",
    ],
    gap: ["gap-gn-1/2", "gap-x-gn-1/2", "gap-y-gn-1/2"],
    space: ["space-x-gn-1/2", "space-y-gn-1/2"],
    inset: [
      "inset-gn-1/2",
      "inset-x-gn-1/2",
      "inset-y-gn-1/2",
      "start-gn-1/2",
      "end-gn-1/2",
      "top-gn-1/2",
      "right-gn-1/2",
      "bottom-gn-1/2",
      "left-gn-1/2",
    ],
  },
  {
    name: "gw-1/2",
    padding: [
      "p-gw-1/2",
      "px-gw-1/2",
      "py-gw-1/2",
      "ps-gw-1/2",
      "pe-gw-1/2",
      "pt-gw-1/2",
      "pr-gw-1/2",
      "pb-gw-1/2",
      "pl-gw-1/2",
    ],
    margin: [
      "m-gw-1/2",
      "mx-gw-1/2",
      "my-gw-1/2",
      "ms-gw-1/2",
      "me-gw-1/2",
      "mt-gw-1/2",
      "mr-gw-1/2",
      "mb-gw-1/2",
      "ml-gw-1/2",
    ],
    gap: ["gap-gw-1/2", "gap-x-gw-1/2", "gap-y-gw-1/2"],
    space: ["space-x-gw-1/2", "space-y-gw-1/2"],
    inset: [
      "inset-gw-1/2",
      "inset-x-gw-1/2",
      "inset-y-gw-1/2",
      "start-gw-1/2",
      "end-gw-1/2",
      "top-gw-1/2",
      "right-gw-1/2",
      "bottom-gw-1/2",
      "left-gw-1/2",
    ],
  },
] as const;

/** Block-axis size utilities rendered in the size token matrix. */
export const blockSizeClasses = [
  "h-3xs",
  "min-h-3xs",
  "max-h-3xs",
  "h-2xs",
  "min-h-2xs",
  "max-h-2xs",
  "h-xs",
  "min-h-xs",
  "max-h-xs",
  "h-sm",
  "min-h-sm",
  "max-h-sm",
  "h-md",
  "min-h-md",
  "max-h-md",
  "h-lg",
  "min-h-lg",
  "max-h-lg",
  "h-xl",
  "min-h-xl",
  "max-h-xl",
  "h-2xl",
  "min-h-2xl",
  "max-h-2xl",
  "h-3xl",
  "min-h-3xl",
  "max-h-3xl",
  "h-4xl",
  "min-h-4xl",
  "max-h-4xl",
  "h-5xl",
  "min-h-5xl",
  "max-h-5xl",
  "h-6xl",
  "min-h-6xl",
  "max-h-6xl",
  "h-7xl",
  "min-h-7xl",
  "max-h-7xl",
  "h-gw",
  "min-h-gw",
  "max-h-gw",
  "h-gn",
  "min-h-gn",
  "max-h-gn",
  "h-gn-2x",
  "min-h-gn-2x",
  "max-h-gn-2x",
  "h-gn-1/2",
  "min-h-gn-1/2",
  "max-h-gn-1/2",
  "h-gw-1/2",
  "min-h-gw-1/2",
  "max-h-gw-1/2",
] as const;

/** Inline-axis size utilities rendered in the size token matrix. */
export const inlineSizeClasses = [
  "w-3xs",
  "min-w-3xs",
  "max-w-3xs",
  "w-2xs",
  "min-w-2xs",
  "max-w-2xs",
  "w-xs",
  "min-w-xs",
  "max-w-xs",
  "w-sm",
  "min-w-sm",
  "max-w-sm",
  "w-md",
  "min-w-md",
  "max-w-md",
  "w-lg",
  "min-w-lg",
  "max-w-lg",
  "w-xl",
  "min-w-xl",
  "max-w-xl",
  "w-2xl",
  "min-w-2xl",
  "max-w-2xl",
  "w-3xl",
  "min-w-3xl",
  "max-w-3xl",
  "w-4xl",
  "min-w-4xl",
  "max-w-4xl",
  "w-5xl",
  "min-w-5xl",
  "max-w-5xl",
  "w-6xl",
  "min-w-6xl",
  "max-w-6xl",
  "w-7xl",
  "min-w-7xl",
  "max-w-7xl",
  "w-gw",
  "min-w-gw",
  "max-w-gw",
  "w-gn",
  "min-w-gn",
  "max-w-gn",
  "w-gn-2x",
  "min-w-gn-2x",
  "max-w-gn-2x",
  "w-gn-1/2",
  "min-w-gn-1/2",
  "max-w-gn-1/2",
  "w-gw-1/2",
  "min-w-gw-1/2",
  "max-w-gw-1/2",
] as const;

/** Max-width container utilities rendered in the layout token matrix. */
export const containerClasses = [
  "max-w-3xs",
  "max-w-2xs",
  "max-w-xs",
  "max-w-sm",
  "max-w-md",
  "max-w-lg",
  "max-w-xl",
  "max-w-2xl",
  "max-w-3xl",
  "max-w-4xl",
  "max-w-5xl",
  "max-w-6xl",
  "max-w-7xl",
  "max-w-gw",
  "max-w-gn",
  "max-w-gn-2x",
  "max-w-gn-1/2",
  "max-w-gw-1/2",
] as const;

/** Border-radius utilities rendered in the shape token matrix. */
export const radiusClasses = [
  "rounded",
  "rounded-sm",
  "rounded-md",
  "rounded-lg",
  "rounded-xl",
  "rounded-2xl",
  "rounded-3xl",
  "rounded-4xl",
] as const;

/** Aspect-ratio utilities rendered in the media token matrix. */
export const aspectClasses = [
  "aspect-golden",
  "aspect-video",
  "aspect-portrait",
  "aspect-retro",
  "aspect-square",
  "aspect-panorama",
  "aspect-imax",
] as const;

/** Animation utilities rendered in the motion token matrix. */
export const animationClasses = [
  "animate-accordion-down",
  "animate-accordion-up",
  "animate-fade-in",
  "animate-fade-in-up",
  "animate-fade-in-up-delay-1",
  "animate-fade-in-up-delay-2",
  "animate-fade-in-up-delay-3",
  "animate-fade-in-up-delay-4",
  "animate-float",
  "animate-pulse-soft",
  "animate-scale-in",
] as const;
